version: '3.3'

services:
  db:
    image: mysql
    container_name: mysql
    volumes:
      - './docker/mysql/data/:/var/lib/mysql'
      - './docker/mysql/config/:/etc/mysql/conf.d'
      - './sql/:/docker-entrypoint-initdb.d'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'todolist'
      MYSQL_USER: 'joybell'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
      TZ: 'Asia/Seoul'
